config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :priorities
  resources :statuses
  resources :sprint_teams
  resources :sprints
  resources :team_users
  resources :teams
  resources :users
  resources :epics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/epic.rb
class Epic < ApplicationRecord
  has_many :tasks
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/sprint.rb
class Sprint < ApplicationRecord
end

app/models/sprint_team.rb
class SprintTeam < ApplicationRecord
  belongs_to :sprint
  belongs_to :team
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :status
  belongs_to :priority
  belongs_to :epic
  belongs_to :assigned_to, class_name: 'User', :foreign_key => :assigned_to_id
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users
  has_many :users, through: :team_users
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks , :foreign_key => :assigned_to_id

  has_many :team_users
  has_many :teams, through: :team_users
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
  before_action :set_epic, only: [:show, :edit, :update, :destroy]

  # GET /epics
  # GET /epics.json
  def index
    @epics = Epic.all
  end

  # GET /epics/1
  # GET /epics/1.json
  def show
  end

  # GET /epics/new
  def new
    @epic = Epic.new
  end

  # GET /epics/1/edit
  def edit
  end

  # POST /epics
  # POST /epics.json
  def create
    @epic = Epic.new(epic_params)

    respond_to do |format|
      if @epic.save
        format.html { redirect_to @epic, notice: 'Epic was successfully created.' }
        format.json { render :show, status: :created, location: @epic }
      else
        format.html { render :new }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epics/1
  # PATCH/PUT /epics/1.json
  def update
    respond_to do |format|
      if @epic.update(epic_params)
        format.html { redirect_to @epic, notice: 'Epic was successfully updated.' }
        format.json { render :show, status: :ok, location: @epic }
      else
        format.html { render :edit }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epics/1
  # DELETE /epics/1.json
  def destroy
    @epic.destroy
    respond_to do |format|
      format.html { redirect_to epics_url, notice: 'Epic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epic
      @epic = Epic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epic_params
      params.require(:epic).permit(:description)
    end
end

app/controllers/sprint_teams_controller.rb
class SprintTeamsController < ApplicationController
  before_action :set_sprint_team, only: [:show, :edit, :update, :destroy]

  # GET /sprint_teams
  # GET /sprint_teams.json
  def index
    @sprint_teams = SprintTeam.all
  end

  # GET /sprint_teams/1
  # GET /sprint_teams/1.json
  def show
  end

  # GET /sprint_teams/new
  def new
    @sprint_team = SprintTeam.new
  end

  # GET /sprint_teams/1/edit
  def edit
  end

  # POST /sprint_teams
  # POST /sprint_teams.json
  def create
    @sprint_team = SprintTeam.new(sprint_team_params)

    respond_to do |format|
      if @sprint_team.save
        format.html { redirect_to @sprint_team, notice: 'Sprint team was successfully created.' }
        format.json { render :show, status: :created, location: @sprint_team }
      else
        format.html { render :new }
        format.json { render json: @sprint_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprint_teams/1
  # PATCH/PUT /sprint_teams/1.json
  def update
    respond_to do |format|
      if @sprint_team.update(sprint_team_params)
        format.html { redirect_to @sprint_team, notice: 'Sprint team was successfully updated.' }
        format.json { render :show, status: :ok, location: @sprint_team }
      else
        format.html { render :edit }
        format.json { render json: @sprint_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprint_teams/1
  # DELETE /sprint_teams/1.json
  def destroy
    @sprint_team.destroy
    respond_to do |format|
      format.html { redirect_to sprint_teams_url, notice: 'Sprint team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprint_team
      @sprint_team = SprintTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sprint_team_params
      params.require(:sprint_team).permit(:sprint_id, :team_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:status_id, :priority_id, :epic_id, :header, :body, :assigned_to_id, :is_trash, :estimate, :remaining_estimate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epics_helper.rb
module EpicsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/sprint_teams_helper.rb
module SprintTeamsHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sprint_teams/_form.html.erb
<%= form_for(sprint_team) do |f| %>
  <% if sprint_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sprint_team.errors.count, "error") %> prohibited this sprint_team from being saved:</h2>

      <ul>
      <% sprint_team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sprint_id %>
    <%= f.text_field :sprint_id %>
  </div>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.text_field :team_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sprint_teams/edit.html.erb
<h1>Editing Sprint Team</h1>

<%= render 'form', sprint_team: @sprint_team %>

<%= link_to 'Show', @sprint_team %> |
<%= link_to 'Back', sprint_teams_path %>

app/views/sprint_teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sprint Teams</h1>

<table>
  <thead>
    <tr>
      <th>Sprint</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sprint_teams.each do |sprint_team| %>
      <tr>
        <td><%= sprint_team.sprint %></td>
        <td><%= sprint_team.team %></td>
        <td><%= link_to 'Show', sprint_team %></td>
        <td><%= link_to 'Edit', edit_sprint_team_path(sprint_team) %></td>
        <td><%= link_to 'Destroy', sprint_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sprint Team', new_sprint_team_path %>

app/views/sprint_teams/new.html.erb
<h1>New Sprint Team</h1>

<%= render 'form', sprint_team: @sprint_team %>

<%= link_to 'Back', sprint_teams_path %>

app/views/sprint_teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sprint:</strong>
  <%= @sprint_team.sprint %>
</p>

<p>
  <strong>Team:</strong>
  <%= @sprint_team.team %>
</p>

<%= link_to 'Edit', edit_sprint_team_path(@sprint_team) %> |
<%= link_to 'Back', sprint_teams_path %>