config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :priorities
  resources :statuses
  resources :sprint_teams
  resources :sprints
  resources :team_users
  resources :teams
  resources :users
  resources :epics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/epic.rb
class Epic < ApplicationRecord
  has_many :tasks
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/sprint.rb
class Sprint < ApplicationRecord
end

app/models/sprint_team.rb
class SprintTeam < ApplicationRecord
  belongs_to :sprint
  belongs_to :team
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :status
  belongs_to :priority
  belongs_to :epic
  belongs_to :assigned_to, class_name: 'User', :foreign_key => :assigned_to_id
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users
  has_many :users, through: :team_users
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks , :foreign_key => :assigned_to_id

  has_many :team_users
  has_many :teams, through: :team_users
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
  before_action :set_epic, only: [:show, :edit, :update, :destroy]

  # GET /epics
  # GET /epics.json
  def index
    @epics = Epic.all
  end

  # GET /epics/1
  # GET /epics/1.json
  def show
  end

  # GET /epics/new
  def new
    @epic = Epic.new
  end

  # GET /epics/1/edit
  def edit
  end

  # POST /epics
  # POST /epics.json
  def create
    @epic = Epic.new(epic_params)

    respond_to do |format|
      if @epic.save
        format.html { redirect_to @epic, notice: 'Epic was successfully created.' }
        format.json { render :show, status: :created, location: @epic }
      else
        format.html { render :new }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epics/1
  # PATCH/PUT /epics/1.json
  def update
    respond_to do |format|
      if @epic.update(epic_params)
        format.html { redirect_to @epic, notice: 'Epic was successfully updated.' }
        format.json { render :show, status: :ok, location: @epic }
      else
        format.html { render :edit }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epics/1
  # DELETE /epics/1.json
  def destroy
    @epic.destroy
    respond_to do |format|
      format.html { redirect_to epics_url, notice: 'Epic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epic
      @epic = Epic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epic_params
      params.require(:epic).permit(:description)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epics_helper.rb
module EpicsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/sprint_teams_helper.rb
module SprintTeamsHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/statuses/_form.html.erb
<%= form_for(status) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.description %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @status.description %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>