config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :priorities
  resources :statuses
  resources :sprint_teams
  resources :sprints
  resources :team_users
  resources :teams
  resources :users
  resources :epics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/epic.rb
class Epic < ApplicationRecord
  has_many :tasks
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/sprint.rb
class Sprint < ApplicationRecord
end

app/models/sprint_team.rb
class SprintTeam < ApplicationRecord
  belongs_to :sprint
  belongs_to :team
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :status
  belongs_to :priority
  belongs_to :epic
  belongs_to :assigned_to, class_name: 'User', :foreign_key => :assigned_to_id
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users
  has_many :users, through: :team_users
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks , :foreign_key => :assigned_to_id

  has_many :team_users
  has_many :teams, through: :team_users
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
  before_action :set_epic, only: [:show, :edit, :update, :destroy]

  # GET /epics
  # GET /epics.json
  def index
    @epics = Epic.all
  end

  # GET /epics/1
  # GET /epics/1.json
  def show
  end

  # GET /epics/new
  def new
    @epic = Epic.new
  end

  # GET /epics/1/edit
  def edit
  end

  # POST /epics
  # POST /epics.json
  def create
    @epic = Epic.new(epic_params)

    respond_to do |format|
      if @epic.save
        format.html { redirect_to @epic, notice: 'Epic was successfully created.' }
        format.json { render :show, status: :created, location: @epic }
      else
        format.html { render :new }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epics/1
  # PATCH/PUT /epics/1.json
  def update
    respond_to do |format|
      if @epic.update(epic_params)
        format.html { redirect_to @epic, notice: 'Epic was successfully updated.' }
        format.json { render :show, status: :ok, location: @epic }
      else
        format.html { render :edit }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epics/1
  # DELETE /epics/1.json
  def destroy
    @epic.destroy
    respond_to do |format|
      format.html { redirect_to epics_url, notice: 'Epic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epic
      @epic = Epic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epic_params
      params.require(:epic).permit(:description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:status_id, :priority_id, :epic_id, :header, :body, :assigned_to_id, :is_trash, :estimate, :remaining_estimate)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastname, :work_hours)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epics_helper.rb
module EpicsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/sprint_teams_helper.rb
module SprintTeamsHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :work_hours %>
    <%= f.number_field :work_hours %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Work hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.work_hours %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Work hours:</strong>
  <%= @user.work_hours %>
</p>

<h2>Tasks</h2>

<table class="table">
  <thead>
    <tr>
      <th>Status</th>
      <th>Priority</th>
      <th>Epic</th>
      <th>Header</th>
      <th>Body</th>
      <th>Assigned to</th>
      <th>Is trash</th>
      <th>Estimate</th>
      <th>Remaining estimate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.status.description %></td>
        <td><%= task.priority.description %></td>
        <td><%= task.epic.description %></td>
        <td><%= task.header %></td>
        <td><%= task.is_trash %></td>
        <td><%= task.estimate %></td>
        <td><%= task.remaining_estimate %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>