config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :priorities
  resources :statuses
  resources :sprint_teams
  resources :sprints
  resources :team_users
  resources :teams
  resources :users
  resources :epics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/epic.rb
class Epic < ApplicationRecord
  has_many :tasks
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/sprint.rb
class Sprint < ApplicationRecord
end

app/models/sprint_team.rb
class SprintTeam < ApplicationRecord
  belongs_to :sprint
  belongs_to :team
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :status
  belongs_to :priority
  belongs_to :epic
  belongs_to :assigned_to, class_name: 'User', :foreign_key => :assigned_to_id
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users
  has_many :users, through: :team_users
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks , :foreign_key => :assigned_to_id

  has_many :team_users
  has_many :teams, through: :team_users
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
  before_action :set_epic, only: [:show, :edit, :update, :destroy]

  # GET /epics
  # GET /epics.json
  def index
    @epics = Epic.all
  end

  # GET /epics/1
  # GET /epics/1.json
  def show
  end

  # GET /epics/new
  def new
    @epic = Epic.new
  end

  # GET /epics/1/edit
  def edit
  end

  # POST /epics
  # POST /epics.json
  def create
    @epic = Epic.new(epic_params)

    respond_to do |format|
      if @epic.save
        format.html { redirect_to @epic, notice: 'Epic was successfully created.' }
        format.json { render :show, status: :created, location: @epic }
      else
        format.html { render :new }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epics/1
  # PATCH/PUT /epics/1.json
  def update
    respond_to do |format|
      if @epic.update(epic_params)
        format.html { redirect_to @epic, notice: 'Epic was successfully updated.' }
        format.json { render :show, status: :ok, location: @epic }
      else
        format.html { render :edit }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epics/1
  # DELETE /epics/1.json
  def destroy
    @epic.destroy
    respond_to do |format|
      format.html { redirect_to epics_url, notice: 'Epic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epic
      @epic = Epic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epic_params
      params.require(:epic).permit(:description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:status_id, :priority_id, :epic_id, :header, :body, :assigned_to_id, :is_trash, :estimate, :remaining_estimate)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:description, :team_hours)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epics_helper.rb
module EpicsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/sprint_teams_helper.rb
module SprintTeamsHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/epics/_form.html.erb
<%= form_for(epic) do |f| %>
  <% if epic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(epic.errors.count, "error") %> prohibited this epic from being saved:</h2>

      <ul>
      <% epic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/epics/edit.html.erb
<h1>Editing Epic</h1>

<%= render 'form', epic: @epic %>

<%= link_to 'Show', @epic %> |
<%= link_to 'Back', epics_path %>

app/views/epics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Epics</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @epics.each do |epic| %>
      <tr>
        <td><%= epic.description %></td>
        <td><%= link_to 'Show', epic %></td>
        <td><%= link_to 'Edit', edit_epic_path(epic) %></td>
        <td><%= link_to 'Destroy', epic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Epic', new_epic_path %>

app/views/epics/new.html.erb
<h1>New Epic</h1>

<%= render 'form', epic: @epic %>

<%= link_to 'Back', epics_path %>

app/views/epics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @epic.description %>
</p>

<h2>Tasks</h2>

<table class="table">
  <thead>
    <tr>
      <th>Status</th>
      <th>Priority</th>
      <th>Epic</th>
      <th>Header</th>
      <th>Body</th>
      <th>Assigned to</th>
      <th>Is trash</th>
      <th>Estimate</th>
      <th>Remaining estimate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @epic.tasks.each do |task| %>
      <tr>
        <td><%= task.status.description %></td>
        <td><%= task.priority.description %></td>
        <td><%= task.epic.description %></td>
        <td><%= task.header %></td>
        <td><%= task.is_trash %></td>
        <td><%= task.estimate %></td>
        <td><%= task.remaining_estimate %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_epic_path(@epic) %> |
<%= link_to 'Back', epics_path %>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :status_id, 'Status' %>
    <%= f.collection_select :status_id, Status.all, :id, :description,
      { :include_blank => true},
      {:class => 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :priority_id, 'Priority' %>
    <%= f.collection_select :priority_id, Priority.all, :id, :description,
      { :include_blank => true},
      {:class => 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :epic_id, 'Epic' %>
    <%= f.collection_select :epic_id, Epic.all, :id, :description,
      { :include_blank => true},
      {:class => 'form-control'} %>
  </div>

  <div class="field">
    <%= f.label :header %>
    <%= f.text_field :header %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>


  <div class="form-group">
    <%= f.label :assigned_to, 'Assigned to' %>
    <%= f.collection_select :assigned_to_id, User.all, :id, :name,
      { :include_blank => true},
      {:class => 'form-control'} %>
  </div>


  <div class="field">
    <%= f.label :is_trash %>
    <%= f.check_box :is_trash %>
  </div>

  <div class="field">
    <%= f.label :estimate %>
    <%= f.datetime_select :estimate %>
  </div>

  <div class="field">
    <%= f.label :remaining_estimate %>
    <%= f.datetime_select :remaining_estimate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Priority</th>
      <th>Epic</th>
      <th>Header</th>
      <th>Assigned to</th>
      <th>Is trash</th>
      <th>Estimate</th>
      <th>Remaining estimate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.status.description %></td>
        <td><%= task.priority.description %></td>
        <td><%= task.epic.description %></td>
        <td><%= task.header %></td>
        <td><%= link_to task.assigned_to.name, task.assigned_to %></td>
        <td><%= task.is_trash %></td>
        <td><%= task.estimate %></td>
        <td><%= task.remaining_estimate %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Epic:</strong>
  <%= @task.epic %>
</p>

<p>
  <strong>Header:</strong>
  <%= @task.header %>
</p>

<p>
  <strong>Body:</strong>
  <%= @task.body %>
</p>

<p>
  <strong>Assigned to:</strong>
  <%= @task.assigned_to %>
</p>

<p>
  <strong>Is trash:</strong>
  <%= @task.is_trash %>
</p>

<p>
  <strong>Estimate:</strong>
  <%= @task.estimate %>
</p>

<p>
  <strong>Remaining estimate:</strong>
  <%= @task.remaining_estimate %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>